### ISSUE TITLE
using x264enc causes Critical caps event error

### ISSUE THREAD

**Issue by tomberthon** [RidgeRun/gst-interpipe#1]
Hi

I'm trying to use Gst-Interpipe to change of sources of content on the fly and output the generated result to HLS streams. 

When using the x264enc encoder with the interpipesrc elements the following error is raised and playback is paused.

> GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed

This pipeline works fine without interpipe, to generate a test stream but I am looking to be able to use interpipe to switch streams when needed.

Sample code attached to show this issue.

Is this an issue with the Caps Negotiation - as it seems that a new caps event is created from x264enc without a "format" parameter.

Is there a way that interpipe could be causing this issue to occur?

[hls.txt](https://github.com/RidgeRun/gst-interpipe/files/366645/hls.txt)

**Comment by rrcarlosrodriguez** [comment]
Hi,

Two days ago we committed a change that may be help you with your problem. Please update your gst-interpipe repo with the latest commit (f3536ebcbd262ea3d362360f43e3af69757ee39f) and try running your test again.

If it doesn't fix the issue, send us your pipeline and we could try to reproduce the issue here and see what happens.

**Comment by tomberthon** [comment]
Hi

Using the updated master has had no affect and this issue is still occurring. The previous attached hls.txt file is the c code that I have been using to create my pipelines.

With debug up to "4" the following lines appear in the output:

> 0:00:00.592738809    27      0x2723140 INFO               GST_EVENT gstevent.c:679:gst_event_new_caps: creating caps event video/x-h264, stream-format=(string)byte-stream, alignment=(string)au, level=(string)1.3, profile=(string)high, width=(int)320, height=(int)240, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)30/1
0:00:00.592932174    27      0x2723140 WARN             collectpads gstcollectpads.c:1810:gst_collect_pads_event_default:<collectpads0> GstCollectPads default collecting can only handle time segments. Non time segment ignored.
>
>(bt-interpipe:27): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment-format == format' failed

The last line is then repeated - by the looks of it - for every frame produced.

All other log messages look to be normal for the pipe to be configuring and playing up until that point..

Any help much appreciated.

**Comment by rrcarlosrodriguez** [comment]
Hi,

We reviewed your code and found some settings that enable the app to run properly:

- Forward-events property to true in the interpipesink.
- Setting caps after the interpipesrc is not necessary

[app-interpipes.txt](https://github.com/RidgeRun/gst-interpipe/files/384869/app-interpipes.txt)

The above code has the mentioned changes and it has the functionality to record a ts file. You can change the sink from filesink to the hlssink and test.

Give it a try and let me know how it works.

**Comment by jcaballeros** [comment]
Closing, feel free to reopen if necessary.
