### ISSUE TITLE
Failed 8 out of 16 tests on Ubuntu 16.04

### ISSUE THREAD

**Issue by Snec** [RidgeRun/gst-interpipe#12]
Similar to [https://github.com/RidgeRun/gst-interpipe/issues/11](https://github.com/RidgeRun/gst-interpipe/issues/11) : I have compiled your gst-interpipe plugin on my 64bit Ubuntu 16.04 PC and after calling "make check" 8 out of 16 tests failed. You can see test logs here: https://pastebin.com/raw/rP2rqXYT

Additional information:

    GStreamer version: 1.8.3
    uname -a: Linux MyMachineName 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    gcc version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by michaelgruner** [comment]
@bperez241 is checking this a per #11 report. Thanks for the report.

**Comment by jcaballeros** [comment]
Hi,

I’m closing this issue because it has been inactive for a long time. Please feel free to reopen if you still encounter a related issue with the latest source code.
