### ISSUE TITLE
Failing test during build - gst/test_stream_sync

### ISSUE THREAD

**Issue by chirag-b** [RidgeRun/gst-interpipe#134]
Hello,

I am trying to build a docker image for the aarch64 platform on my x86_64 platform. I am trying to build gst-interpipes inside the image and the gst/test_stream_sync test is failing. Is there something I can do? 

I see the error message **"Unexpected critical/warning: gst_caps_intersect_full: assertion 'GST_IS_CAPS (caps1)' failed"** in the test-suite.log.

Here is the test-suite.log file
[test-suite.log](https://github.com/RidgeRun/gst-interpipe/files/9419256/test-suite.log)

Thank you

**Comment by jagtonomy** [comment]
I am facing the same problem. Has this been resolved?
