### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by rahul-bedarkar** [RidgeRun/gst-interpipe#16]
Hello,

All source files under gst/interpipe have license header for  LGPL 2 or later. But license file COPYING and README.md says LGPL 2.1.

Please clarify this license inconsistency.

Thanks,
Rahul

**Comment by fischer** [comment]
Rahul,

Thanks for pointing out the inconsistency.  The goal is to match the license used by other GStreamer elements, which use the LGPL 2 license.  The COPYING and README.md will be modified accordingly.

**Comment by bunder** [comment]
In `GST_PLUGIN_DEFINE()` license is set to "Proprietary".

**Comment by fischer** [comment]
bunder, good catch.  Fixed with commit 0a4fe03 on a branch.  After review it will be merged into master.
