### ISSUE TITLE
gst_segment_to_running_time: assertion 'segment->format == format' failed

### ISSUE THREAD

**Issue by Harishrelysys** [RidgeRun/gst-interpipe#17]
Hi all,
        I am using the following gst-interpipe commands,I am getting the video but i am getting following error.Please help me if I am missing anything in the command 

Thank you all in advance

**command:**
```
gstd-client pipeline_create video0src videotestsrc ! queue ! interpipesink name=video0_src sync=false async=false \
gstd-client pipeline_create video0mainsrc interpipesrc name=src is-live=true listen-to=video0_src ! queue ! omxh264enc target-bitrate=2097152 num-p-frames=0 ! rtph264pay pt=96 name=pay0 config-interval=3 ! queue ! udpsink host=127.0.0.1 port=5000

```
```
gstd-client pipeline_play video0src
gstd-client pipeline_play video0mainsrc
```
**Error log:**
(gstd:753): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed
(gstd:753): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed
(gstd:753): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed
(gstd:753): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed
(gstd:753): GStreamer-CRITICAL **: gst_segment_to_running_time: assertion 'segment->format == format' failed

I am getting this error continuously 

gstd version:0.6.2
gstreamer version:1.2.3

**Comment by jdnewman85** [comment]
I also get this with these versions of everything: Archlinux 4.18.7 Gstreamer 1.14.2 Interpipe 1.0.2

**Comment by michaelgruner** [comment]
Can you try setting `interpipesrc format=time`

**Comment by Harishrelysys** [comment]
Thanks for replying,
 I will try this

**Comment by RSATom** [comment]
Got the same issue, fixed by https://github.com/RidgeRun/gst-interpipe/pull/21

**Comment by jcaballeros** [comment]
Hi,
I’m closing this issue because it has been inactive for a long time. Please feel free to reopen if you still encounter a related issue with the latest source code.

**Comment by dlwalter** [comment]
In c++ this is solved by
`g_object_set(G_OBJECT(interpipesrc), "format", GST_FORMAT_TIME, NULL);`

**Comment by vijaykarthikeyanvvk98** [comment]
> In c++ this is solved by `g_object_set(G_OBJECT(interpipesrc), "format", GST_FORMAT_TIME, NULL);`

thank you..it works
