### ISSUE TITLE
gst_segment_to_running_time: assertion 'segment->format == format' failed  When using rtpulpfecdec element

### ISSUE THREAD

**Issue by ghost** [RidgeRun/gst-interpipe#19]
Hi I am building one application based on rust file examples of _rtpulpfecdec_ and  _rtpulpfecenc_ 
.I am adding 20% of fec packets but on the receiving side ,recovered packets are stopped after some time and giving an assertion as follows,
_gst_segment_to_running_time: assertion 'segment->format == format' failed_

**Comment by michaelgruner** [comment]
Can you try setting the format manually? Something like `interpipesrc format=time`.

**Comment by jcaballeros** [comment]
Hi,
I’m closing this issue because it has been inactive for a long time. Please feel free to reopen if you still encounter a related issue with the latest source code.
