### ISSUE TITLE
Master failing tests

### ISSUE THREAD

**Issue by superlou** [RidgeRun/gst-interpipe#2]
I installed the latest master today on Linux Mint 18 with GStreamer 1.8.2.  After `make check`, I received the following results:

After building, I had 4 failing test cases:

```
PASS: gst/test_buffer_properties
PASS: gst/test_node_name_removed
FAIL: gst/test_hot_plug
PASS: gst/test_block_switch
FAIL: gst/test_allow_renegotiation_property
FAIL: gst/test_get_caps
PASS: gst/test_set_caps
FAIL: gst/test_caps_renegotiation
PASS: gst/test_interpipe_synchronization
PASS: gst/test_anonymous_connection
PASS: gst/test_reconfigure_event
PASS: gst/test_invalid_caps
PASS: gst/test_out_of_bounds_events
PASS: gst/test_in_bounds_events
PASS: gst/test_out_of_bounds_upstream_events
PASS: gst/test_enable_sync
============================================================================
Testsuite summary for GstInterpipe 1.0.0.1
============================================================================
# TOTAL: 16
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0
```

Is this expected for the code on Github master?

**Comment by rrcarlosrodriguez** [comment]
Hi,

No, this is not expected. We will be checking the problem. Could you attach the output of the test-suite.log found in tests/check/ directory please?

**Comment by superlou** [comment]
Please see the attached log: [test-suite.log.txt](https://github.com/RidgeRun/gst-interpipe/files/385052/test-suite.log.txt)

**Comment by superlou** [comment]
As further debug info which may be related, the following example from the wiki gives warnings:

```
 gst-launch-1.0 \
> videotestsrc ! interpipesink name=camera \
> interpipesrc listen-to="camera" ! fakesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...

(gst-launch-1.0:5867): GStreamer-WARNING **: gstpad.c:5053:store_sticky_event:<interpipesrc0:src> Sticky event misordering, got 'segment' before 'caps'

(gst-launch-1.0:5867): GStreamer-WARNING **: gstpad.c:5053:store_sticky_event:<fakesink0:sink> Sticky event misordering, got 'segment' before 'caps'
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
```

If I try to use ximagesinks, I do get the videotestsrc video in a new window.  However, if I try to run the two halves of the example in different bash shells, they don't seem to link.

Video Source:
```
gst-launch-1.0 videotestsrc ! interpipesink name=camera
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
```

Video Display:
```
gst-launch-1.0 interpipesrc listen-to="camera" ! ximagesink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
```

No video is displayed.  Is interpipesrc similar to intervideosrc in that it will attempt to generate black frames if there is no data coming in, or must an interpipesrc always be listening to something?

**Comment by michaelgruner** [comment]
Hi, yes Interpipes will only work if the pipelines are in the same process. Hence, using two independent gst-launch commands will no work. To achieve a similar effect, you may try [Gstreamer Daemon](https://github.com/RidgeRun/gstd-1.x), which will allow you to start pipelines on different shells, but they are all handled by the same process. As per now, Gstd has basic functionality like playing, pausing, nulling and setting/getting element properties. We are working to finish existing features and add new ones for more advanced use cases.

**Comment by superlou** [comment]
Getting off track from the original issue, I guess, but is it enough for only the pipelines to be in the same process?  Do you still get the advantage of queues allowing multiple threads to run in parallel?  With regards to generating data black frames or audience silence when a src is not listening to a sink, is that going to be a new feature down the road?

**Comment by jcaballeros** [comment]
Hi,

Yes, queues enable multithreading. Currently, there is no plan to develop the feature of generating empty-buffers. Something like this could be achieved with an additional pipe with a fakesrc ! interpipesink that can be connected to the interpipesrc when it's listen-to property is null.

Closing, feel free to reopen if necessary.
