### ISSUE TITLE
"make check" fails

### ISSUE THREAD

**Issue by cls22** [RidgeRun/gst-interpipe#24]
When running "make check", one of the tests failed:-
"$ more tests/check/test-suite.log ====================================================
   GstInterpipe 1.0.4: tests/check/test-suite.log
====================================================

# TOTAL: 16
# PASS:  15
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: gst/test_get_caps
======================="

Running suite(s): Interpipe
66%: Checks: 3, Failures: 1, Errors: 0
gst/test_get_caps.c:250:F:get_caps_two_interpipesrcs_no_intersection:interpipe_get_caps_two_interpipesrcs_no_interse
ction:0: Failure 'GST_STATE_CHANGE_FAILURE == gst_element_get_state (GST_ELEMENT (src1), NULL, NULL, GST_CLOCK_TIME_
NONE)' occurred
FAIL gst/test_get_caps (exit status: 1)

I am building this with the following system configuration:
lee@lee-VirtualBox:/media/sf_Share/workspace-HaWC/gst-interpipe$ uname -a
Linux lee-VirtualBox 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
lee@lee-VirtualBox:/media/sf_Share/workspace-HaWC/gst-interpipe$ gst-launch-1.0 --gst-version
GStreamer Core Library version 1.8.3

Cheers,

Lee

**Comment by TopperBG** [comment]
I think you need Gstreamer 1.10 and above

**Comment by jcaballeros** [comment]
Hi,

GstInterpipe does work in GStreamer 1.8.

I’m closing this issue because it has been inactive for a long time. Please feel free to reopen if you still encounter a related issue with the latest source code.
