### ISSUE TITLE
storeing mpegts file storing only audio gstreamer 

### ISSUE THREAD

**Issue by Harishrelysys** [RidgeRun/gst-interpipe#25]
Hi All,
         I am trying to encode video and audio and storing it as mpegts my command is 
**command:**
```
gstd-client pipeline_create video0src v4l2src device=/dev/video0 ! vspmfilter outbuf-alloc=true !  video/x-raw,width=640,height=480 ! videorate ! video/x-raw,width=640,height=480,framerate=6/1 ! omxh264enc target-bitrate=2097152 ! mpegtsmux name="muxer" !  \
filesink location=/home/root/testvideo.mpegts \
alsasrc device=hw:0,0 latency-time=30000 buffer-time=800000 ! queue ! audioconvert ! queue ! faac bitrate=128000 ! aacparse ! muxer.
```
this command is working fine and I an getting testvideo.mpegts file with both audio and video.

when i change this command with interpipe elements my command id

**command:**
```
gstd-client pipeline_create video0src v4l2src device=/dev/video0  \
! vspmfilter outbuf-alloc=true ! video/x-raw,width=640,height=480 ! videorate \
! video/x-raw,width=640,height=480,framerate=6/1 ! queue ! interpipesink name=video0_src

gstd-client pipeline_create video0mainsrc interpipesrc is-live=true listen-to=video0_src do-timestamp=true ! queue ! omxh264enc target-bitrate=2097152 ! h264parse ! video/x-h264,stream-format=avc,width=640,height=480,mapping=/stream ! interpipesink name=video0_main sync=false async=false caps=video/x-h264,width=640,height=480

gstd-client pipeline_create video0storing interpipesrc is-live=true listen-to=video0_main do-timestamp=true ! queue ! h264parse config-interval=1 ! \
mpegtsmux name="muxer" ! filesink location=/home/root/testvideo.mpegts \
alsasrc device=hw:0,0 latency-time=30000 buffer-time=800000 ! queue ! audioconvert ! queue ! faac bitrate=128000 ! aacparse ! audio/mpeg,mapping=/audio ! queue ! tee name=aud ! queue ! rtspsink service=8554 \
aud. ! aacparse ! audio/mpeg ! muxer.
```
I am using 3 different pipelines like above to store video but i am getting only audio no video is storing.please help me am i doing anything wrong.

**gstreamer version:1.12.2**

Thank you all

**Comment by michaelgruner** [comment]
We have experienced problems with mpegtsmux before. @mmontero I recall you had some insight regarding this, do you think it applies to this case?

**Comment by Harishrelysys** [comment]
Hi michaelgruner,
                 We had solved this problem,video is now storing with audio properly thanks for the reply.

Thank you

**Comment by fischer** [comment]
@Harishrelysys , can you please share how you solved the problem then close the issue?

**Comment by Harishrelysys** [comment]
Hi michaelgruner,
                           I had updated gstreamer-deamon (gstd-0.7.0) I got 2 clients gstd-client and gst-client-1.0 I am bit confused with these two in previous version we had only gstd-client.So please explain which one I should use.

gstreamer:-1.12.1
kenel:-4.4.138

**Comment by michaelgruner** [comment]
Hi, they are just symbolic links. They all point to the same executable. We kept gstd-client for backwards compatibility, but gst-client-1.0 is more in line with GStreamer naming convention.

**Comment by Harishrelysys** [comment]
Hi michaelgruner,
But now i am not getting gstd-client I can see that executable but i can't run  gstd-client.I can run only gst-client-1.0.Thanks for the quick reply

**Comment by michaelgruner** [comment]
I double-checked and here's these binaries get installed:

```
make install DESTDIR=/tmp/gstd/

tree /tmp/gstd/
/tmp/gstd/
└── usr
    └── local
        ├── bin
        │   ├── gst-client -> /tmp/gstd/usr/local/bin/gst-client-1.0
        │   ├── gst-client-1.0
        │   ├── gstd
        │   └── gstd-client -> /tmp/gstd/usr/local/bin/gst-client-1.0
```

So both `gst-client` and `gstd-client` should exist, and be symlinks to `gst-client-1.0`.

Did you get an error installing? I'd try to manually remove `gstd-client` and reinstall.

**Comment by Harishrelysys** [comment]
Hi michaelgruner,
                            Thanks for the answer.I had built gstd in yocto I got some error while building but i resolved it.I have all these binaries in /usr/bin directory.But when I give gstd-client it says no command gstd-client.Is their any issue if I use gst-client-1.0 instead of gstd-client

**Comment by TopperBG** [comment]
Make than symlink or use gst-client-1.0 - it's the same

**Comment by Harishrelysys** [comment]
Hi TopperBG,
                     Thanks for the reply,I will use gst-client-1.0 only

**Comment by jcaballeros** [comment]
Hi,
I’m closing this issue because it has been inactive for a few months. Please feel free to reopen if you still encounter a related issue with the latest source code.
