### ISSUE TITLE
Can't locate gtkdoc-common.pl

### ISSUE THREAD

**Issue by tylercubell** [RidgeRun/gst-interpipe#26]
On Ubuntu 18.04.1 LTS, I'm getting this error despite installing gtk-doc-tools:

> Can't locate gtkdoc-common.pl in @INC (@INC contains: /usr/share/gtk-doc/data /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ../../common/gstdoc-scangobj line 38.

The only way I can build is by:

```bash
./autogen.sh --noconfigure

./configure --libdir /usr/lib/x86_64-linux-gnu/gstreamer-1.0/ --disable-gtk-doc

make
```

**Comment by RSATom** [comment]
If I remember correctly the reason is outdated `common` subrepo. So just update it to the latest version and all will work as expected.

**Comment by michaelgruner** [comment]
I've updated the `common` subrepo to the latest version in develop. I did not experience the issue myself, can you confirm this fixes it? If it does, I'll merge into master.

**Comment by RSATom** [comment]
@michaelgruner, it's possible you are using older ubuntu (or some other distribution). I've met it on Ubuntu 18.x But it was some months ago, so I can forget someting... let's wait @tylercubell  answer.

**Comment by michaelgruner** [comment]
Let me re-check on my side.

**Comment by jcaballeros** [comment]
Hi,

The latest release v1.1.3 included a fix to a problem related to the common version.

I’m closing this issue because it has been inactive for a few months. Please feel free to reopen if you still encounter a related issue with the latest source code.
