### ISSUE TITLE
Clockoverlay won't show but pipe works 

### ISSUE THREAD

**Issue by TopperBG** [RidgeRun/gst-interpipe#28]
Have few pipes and just one which streaming mpegts has clockoverlay.
Another two recording to file and showing livepreview works but w/o clockoverlay.
That's the source
`pipeline_create cam_src_pipe imxv4l2videosrc typefind=true ! imxipuvideotransform deinterlace=true ! interpipesink name=cam_src caps=video/x-raw,width=640,height=480,framerate=25/1 sync=true async=false forward-eos=true`

That's wont show any clock overlay:
`pipeline_create live_preview_pipe interpipesrc name=live_prev_intpsrc listen-to=cam_src is-live=true allow-renegotiation=true enable-sync=true ! queue max-size-buffers=3 leaky=downstream flush-on-eos=true ! clockoverlay ! videoconvert ! imxg2dvideosink window-width=640 window-height=480 window-x-coord=800 window-y-coord=400`

That's wont show too:
`pipeline_create recording_pipe interpipesrc name=rec_intpsrc listen-to=cam_src is-live=true allow-renegotiation=true enable-sync=false format=time ! clockoverlay halignment=left valignment=bottom ! queue max-size-buffers=3 leaky=downstream ! imxvpuenc_h264 bitrate=8192 ! h264parse ! splitmuxsink location=/tmp/rec_%03d.mpg max-size-time=60000000000 max-files=4 muxer=mpegtsmux
`
**BUT that one works without any problem:**
`pipeline_create stream_pipe interpipesrc name=stream_intpsrc listen-to=cam_src is-live=true allow-renegotiation=true enable-sync=false ! queue max-size-buffers=4 leaky=downstream flush-on-eos=true ! clockoverlay shaded-background=true font-desc="Nimbus mono" valignment=1 ! textoverlay shaded-background=true font-desc="Nimbus mono" valignment=1 halignment=2 text="42.1233N 24.1234E" ! imxvpuenc_h264 bitrate=6000 gop-size=16 ! mpegtsmux ! tcpserversink host=0.0.0.0 port=1234 sync=true`
Both problematic pipes are with different place of clock sink to test the defect.
Any ideas what's could be a problem ?
Version of interpipe plugin is:
 
> gst-inspect-1.0 interpipe
> Plugin Details:
>   Name                     interpipe
>   Description              Elements to communicate buffers across pipelines
>   Filename                 /usr/lib/arm-linux-gnueabihf/gstreamer-1.0/gstreamer-1.0/libgstinterpipe.so
>   Version                  1.0.4
>   License                  Proprietary
>   Source module            gst-interpipe
>   Binary package           GstInterpipe
>   Origin URL               http://www.ridgerun.com
> 
>   interpipesink: Internal pipeline sink
>   interpipesrc: Inter pipeline source
> 
>   2 features:
>   +-- 2 elements
> 

GSTD is the latest commit in dev branch

> commit 0546757b7e7c2fb5f5ca489ac6ee0d668c369936
> Merge: f1747c7 41a4c43
> Author: eramirez392 <enrique.ramirez@ridgerun.com>
> Date:   Wed Jan 9 16:26:01 2019 -0600
> 
>     Merge branch 'feature/fix-docs-build' into develop

**Comment by michaelgruner** [comment]
Thanks for reporting this. @GFallasRR can you go ahead and analyze this issue?

**Comment by TopperBG** [comment]
If the clock/text overlay is put in source pipe - works and that's enough for me.
But in other pipes it didn't except stream_pipe. Should be a problem IMHO.
