### ISSUE TITLE
Request: How to do pipe monitor ?

### ISSUE THREAD

**Issue by TopperBG** [RidgeRun/gst-interpipe#33]
Have few pipes connected to one source (record, stream, stream2, snapshot etc.)
Sometimes record pipe works as design, sometimes stops at 52Kb/148Kb saved. There is somekind of logic because lenght is the same almost all the time but can't catch and reproduce it 100%.
Now I'm thinking about monitoring health of pipe with bus_filter warning,errors & bus_read. And respectively to re-start the pipe with pipeline_play ?
Did someone make anything like this to share it ?

**Comment by michaelgruner** [comment]
Every pipeline gets its own bus, which you can install a callback to monitor for errors. Are you using gstd? Or are you writing an app?

**Comment by TopperBG** [comment]
Yes I'm using GSTd and know about buses but don't have idea how to use it. Now I'm building 5 pipes with bash script in which I'd test play/stop with bus messages and then put all out pipes to pause.
The problem with stalled record pipe IDK where to dig ... another pipes like stream1/stream2/snapshot still working flawless.

**Comment by jcaballeros** [comment]
Hi,
Check the [Gstd wiki](https://developer.ridgerun.com/wiki/index.php?title=GStreamer_Daemon_-_Receiving_Messages_from_the_Bus) to see how to listen to error messages from a pipeline bus.

**Comment by jcaballeros** [comment]
Closing, feel free to reopen if necessary.
