### ISSUE TITLE
16 out of 16 tests fail on macOS 10.14.5

### ISSUE THREAD

**Issue by zWaR** [RidgeRun/gst-interpipe#35]
Hey there,

I've tired to build gst-interpipe on macOS 10.14.5 using this steps:

```bash
#!/usr/bin/env bash


brew install gtk-doc automake autoconf libffi gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

./autogen.sh --noconfigure
./configure --libdir /usr/local/Cellar/gstreamer/1.16.0_1/lib --enable-gtk-doc-html=no
make
make check
make install
```
(I chose to build without gtk-doc, because otherwise `gtkdoc-common.pl` was not found and make did not complete. On linux `gtkdoc-common.pl` seems to be part of `gtk-doc-tools`, but I was not able to find that for macOS.)

However all 16 unit tests fail when I run `make check`. Is it possible to build gst-interpipe on macOS 10.14.5?

GStreamer version: 1.16.0

Thanks!

**Comment by michaelgruner** [comment]
I use interpipes with Mojave without problems. Homebrew is also my preferred package manager. I usually don't install the plug-ins to Gstreamer's cellar, just drop them to `/usr/local/lib/gstreamer-1.0` as usual. The following is what I use:

```bash
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"

./autogen.sh --noconfigure
./configure --disable-gtk-doc
make
make check
make install
```

**Comment by jcaballeros** [comment]
Closing. Feel free to reopen if necessary.
