### ISSUE TITLE
Digital Camera Example Flush Error

### ISSUE THREAD

**Issue by Marc0109** [RidgeRun/gst-interpipe#36]
Hello,
I get an error 16 when "gstd-client event_flush_start recording_pipe" or "gstd-client event_flush_stop recording_pipe false" is called in your digital camera example. I cannot get the example to work. I checked out the top revision of the common subrepo because in the latest release I got an error during build (see #26). The build and also the checks ran successfully. We use NVidia Jetson Nano platform.

Response Error:

{
  "code" : 16,
  "description" : "Event error",
  "response" : null
}

How can I get the flush event to work?

Thanks in advance

Marc

**Comment by jcaballeros** [comment]
Hi,

What gstd version are you using? Can you share your pipeline?

Thanks

**Comment by jcaballeros** [comment]
Closing, feel free to reopen if necessary.
