### ISSUE TITLE
Interpipe with RGB format

### ISSUE THREAD

**Issue by jpeeee** [RidgeRun/gst-interpipe#37]
Hi,
I'm trying to use interpipe with an RGB video source, but I am getting the following error.
`"videotestsrc ! video/x-raw,format=xRGB ! interpipesink name=camera sync=false"`
`"interpipesrc name=display listen-to=camera accept-events=false accept-eos-event=false enable-sync=false allow-renegotiation=false ! autovideosink sync=false async=false"`

0:00:00.057117808  4839 0x5555559ad320 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<display> error: Internal data stream error.
0:00:00.057123026  4839 0x5555559ad320 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<display> error: streaming stopped, reason not-negotiated (-4)

Does interpipe not support RGB formats (in the same way that intervideosrc does not either)?
If so, why not? What's involved in adding support for it? Can you provide pointers to to so? 
Thanks

**Comment by jcaballeros** [comment]
Hi,

Sorry for the late response. Likely the problem was that the autovideosink sink pad didn't accept the xRGB format, so you could add a videoconvert before the autovideosink to make the pipeline work with xRGB.

**Comment by jcaballeros** [comment]
Closing, feel free to reopen if necessary.
