### ISSUE TITLE
Could not connect to local host: Connection refused

### ISSUE THREAD

**Issue by dvescovi1** [RidgeRun/gst-interpipe#40]
I rebuild gstd and interpipe for the imx8m (ARM64) and everything seemed to go well. I verified gstd is working. gst-inspect-1.0 alos shows all the interpipe elements as expected.
root@imx8mmwasp:~# gst-inspect-1.0 interpipe
Plugin Details:
  Name                     interpipe
  Description              Elements to communicate buffers across pipelines
  Filename                 /usr/lib/gstreamer-1.0/libgstinterpipe.so
  Version                  1.0.4
  License                  Proprietary
  Source module            gst-interpipe
  Binary package           GstInterpipe
  Origin URL               http://www.ridgerun.com

  interpipesrc: Inter pipeline source
  interpipesink: Internal pipeline sink

  2 features:
  +-- 2 elements

 I am trying to run the test scripts cctv.sh and camera.sh and I get these connection refused:

root@imx8mmwasp:~# ./cctv.sh

 ====== CCTV Example (Switch the scr_pipe to listen in runtime) ======

 ====> Create the scr_pipe_1

Could not connect to localhost: Connection refused

 ====> Create the scr_pipe_2

Could not connect to localhost: Connection refused

 ====> Create the scr_pipe_3

Could not connect to localhost: Connection refused

 ====> Create the sink_pipe_4 (listener)

Could not connect to localhost: Connection refused

 ====> Change to PLAYING STATE

Could not connect to localhost: Connection refused
Could not connect to localhost: Connection refused
Could not connect to localhost: Connection refused
Could not connect to localhost: Connection refused

 ====> Every 3 seconds the sink_pipe will change the src_pipe that is listening to

 ====> Start listening to scr_pipe_1

any idea what could be causing this?

**Comment by dvescovi1** [comment]
I also verified I can ping localhost and 127.0.0.1 although I don't know what that has to do with anything.

**Comment by michaelgruner** [comment]
Looks like GStreamer Daemon is not running. Did you start it?

**Comment by dvescovi1** [comment]
yea that was initial problem . Now have it started with gstd &  launching ./cctv.sh:
I get:
root@imx8mmwasp:~#
root@imx8mmwasp:~# gstd &
[1] 3383
root@imx8mmwasp:~# ./cctv.sh

 ====== CCTV Example (Switch the scr_pipe to listen in runtime) ======


 ====> Create the scr_pipe_1

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "properties" : [
        {
            "name" : "name",
            "value" : "\"pipe_1_src\"",
            "param_spec" : {
                "blurb" : "The name of the current Gstd session",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "description",
            "value" : "\"videotestsrc pattern=ball is-live=true ! video/x-raw, framerate=15/1, width=640, height=480 ! queue ! interpipesink name=src_1 caps=video/x-raw,width=640,height=480,framerate=15/1 sync=false async=false\"",
            "param_spec" : {
                "blurb" : "The gst-launch like pipeline description",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "elements",
            "value" : "((GstdList*) 0x33c5f330)",
            "param_spec" : {
                "blurb" : "The elements in the pipeline",
                "type" : "GstdList",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "bus",
            "value" : "((GstdPipelineBus*) 0xffff8c028880)",
            "param_spec" : {
                "blurb" : "The bus callback for this element",
                "type" : "GstdPipelineBus",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "state",
            "value" : "((GstdState*) 0xffff8c028070)",
            "param_spec" : {
                "blurb" : "The state of the pipeline",
                "type" : "GstdState",
                "access" : "((GstdParamFlags) READ | UPDATE | 226)",
                "construct" : false
            }
        },
        {
            "name" : "event",
            "value" : "((GstdEventHandler*) 0xffff8c03b860)",
            "param_spec" : {
                "blurb" : "The event handler of the pipeline",
                "type" : "GstdEventHandler",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        }
    ]
}
}

 ====> Create the scr_pipe_2

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "properties" : [
        {
            "name" : "name",
            "value" : "\"pipe_2_src\"",
            "param_spec" : {
                "blurb" : "The name of the current Gstd session",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "description",
            "value" : "\"videotestsrc pattern=snow is-live=true ! video/x-raw, framerate=15/1, width=640, height=480 ! queue ! interpipesink name=src_2 caps=video/x-raw,width=640,height=480,framerate=15/1 sync=false async=false\"",
            "param_spec" : {
                "blurb" : "The gst-launch like pipeline description",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "elements",
            "value" : "((GstdList*) 0xffff8c020f20)",
            "param_spec" : {
                "blurb" : "The elements in the pipeline",
                "type" : "GstdList",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "bus",
            "value" : "((GstdPipelineBus*) 0xffff8c0288f0)",
            "param_spec" : {
                "blurb" : "The bus callback for this element",
                "type" : "GstdPipelineBus",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "state",
            "value" : "((GstdState*) 0xffff8c020240)",
            "param_spec" : {
                "blurb" : "The state of the pipeline",
                "type" : "GstdState",
                "access" : "((GstdParamFlags) READ | UPDATE | 226)",
                "construct" : false
            }
        },
        {
            "name" : "event",
            "value" : "((GstdEventHandler*) 0xffff8c14c5e0)",
            "param_spec" : {
                "blurb" : "The event handler of the pipeline",
                "type" : "GstdEventHandler",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        }
    ]
}
}

 ====> Create the scr_pipe_3

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "properties" : [
        {
            "name" : "name",
            "value" : "\"pipe_3_src\"",
            "param_spec" : {
                "blurb" : "The name of the current Gstd session",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "description",
            "value" : "\"videotestsrc pattern=smpte is-live=true ! video/x-raw, framerate=15/1, width=640, height=480 ! queue ! interpipesink name=src_3 caps=video/x-raw,width=640,height=480,framerate=15/1 sync=false async=false\"",
            "param_spec" : {
                "blurb" : "The gst-launch like pipeline description",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "elements",
            "value" : "((GstdList*) 0xffff8c036380)",
            "param_spec" : {
                "blurb" : "The elements in the pipeline",
                "type" : "GstdList",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "bus",
            "value" : "((GstdPipelineBus*) 0xffff8c14e840)",
            "param_spec" : {
                "blurb" : "The bus callback for this element",
                "type" : "GstdPipelineBus",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "state",
            "value" : "((GstdState*) 0xffff8c028b20)",
            "param_spec" : {
                "blurb" : "The state of the pipeline",
                "type" : "GstdState",
                "access" : "((GstdParamFlags) READ | UPDATE | 226)",
                "construct" : false
            }
        },
        {
            "name" : "event",
            "value" : "((GstdEventHandler*) 0xffff8c04f360)",
            "param_spec" : {
                "blurb" : "The event handler of the pipeline",
                "type" : "GstdEventHandler",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        }
    ]
}
}

 ====> Create the sink_pipe_4 (listener)

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "properties" : [
        {
            "name" : "name",
            "value" : "\"pipe_4_sink\"",
            "param_spec" : {
                "blurb" : "The name of the current Gstd session",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "description",
            "value" : "\"interpipesrc name=interpipesrc1 listen-to=src_1 is-live=true allow-renegotiation=true enable-sync=true ! queue ! fpsdisplaysink async=false sync=false\"",
            "param_spec" : {
                "blurb" : "The gst-launch like pipeline description",
                "type" : "gchararray",
                "access" : "((GstdParamFlags) READ | 234)",
                "construct" : false
            }
        },
        {
            "name" : "elements",
            "value" : "((GstdList*) 0xffff8c036480)",
            "param_spec" : {
                "blurb" : "The elements in the pipeline",
                "type" : "GstdList",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "bus",
            "value" : "((GstdPipelineBus*) 0xffff8c058ed0)",
            "param_spec" : {
                "blurb" : "The bus callback for this element",
                "type" : "GstdPipelineBus",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        },
        {
            "name" : "state",
            "value" : "((GstdState*) 0xffff8c058e60)",
            "param_spec" : {
                "blurb" : "The state of the pipeline",
                "type" : "GstdState",
                "access" : "((GstdParamFlags) READ | UPDATE | 226)",
                "construct" : false
            }
        },
        {
            "name" : "event",
            "value" : "((GstdEventHandler*) 0xffff8c069aa0)",
            "param_spec" : {
                "blurb" : "The event handler of the pipeline",
                "type" : "GstdEventHandler",
                "access" : "((GstdParamFlags) READ | 224)",
                "construct" : false
            }
        }
    ]
}
}

 ====> Change to PLAYING STATE

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "name" : "state",
    "value" : "PLAYING",
    "param_spec" : {
        "[   29.947291] audit: type=1701 audit(1577676742.621:3): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=3383 comm="queue3:src" exe="/usr/bin/gstd" sig=11 res=1
blurb" : "The state of the pipeline",
        "type" : "GstdStateEnum",
        "access" : "((GstdParamFlags) READ | 2)",
        "construct" : false
    }
}
}
{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "name" : "state",
    "value" : "PLAYING",
    "param_spec" : {
        "blurb" : "The state of the pipeline",
        "type" : "GstdStateEnum",
        "access" : "((GstdParamFlags) READ | 2)",
        "construct" : false
    }
}
}
{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "name" : "state",
    "value" : "PLAYING",
    "param_spec" : {
        "blurb" : "The state of the pipeline",
        "type" : "GstdStateEnum",
        "access" : "((GstdParamFlags) READ | 2)",
        "construct" : false
    }
}
}
{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "name" : "state",
    "value" : "PAUSED",
    "param_spec" : {
        "blurb" : "The state of the pipeline",
        "type" : "GstdStateEnum",
        "access" : "((GstdParamFlags) READ | 2)",
        "construct" : false
    }
}
}

** (gstd:3383): CRITICAL **: gst_video_info_from_caps: assertion 'caps != NULL' failed

 ====> Every 3 seconds the sink_pipe will change the src_pipe that is listening to


 ====> Start listening to scr_pipe_1

Could not connect to localhost: Connection refused

 ====> Change to listening to scr_pipe_2

Could not connect to localhost: Connection refused

 ====> Change to listening to scr_pipe_3

^CCould not connect to localhost: Connection refused
Could not connect to localhost: Connection refused
Could not connect to localhost: Connection refused
Could not connect to localhost: Connection refused

 ====> CCTV Example Finished!!!

**Comment by dvescovi1** [comment]
got it working! Had to change the cctv sink segment too:
echo -e "\n ====> Create the sink_pipe_4 (listener) \n"
gstd-client pipeline_create pipe_4_sink interpipesrc name=interpipesrc1 listen-to=src_1 \
is-live=true allow-renegotiation=true enable-sync=true ! queue ! videoconvert ! autovideosink async=false sync=false

adding the extra videoconvert seems to have fixed the issue.
