### ISSUE TITLE
Problem with audio

### ISSUE THREAD

**Issue by hjanuschka** [RidgeRun/gst-interpipe#41]
```
filesrc location=/home/jumanji.mp4 !
    qtdemux name=demux
      demux.audio_0 ! queue ! decodebin ! audioconvert ! audio/x-raw ! audioresample  ! queue ! interpipesink name=audio_source1  sync=false caps=audio/x-raw
     demux.video_0 ! queue ! decodebin ! videoconvert ! videoscale  ! videorate ! video/x-raw,width=1920,height=1080,framerate=25/1 ! interpipesink name=video_source1  sync=true caps=video/x-raw,width=1920,height=1080,framerate=25/1

videotestsrc pattern=black is-live=true ! video/x-raw,width=1920,height=1080,framerate=25/1 ! interpipesink name=s1 \

interpipesrc name=audiocompositor listen-to=audio_source1 ! queue ! audio/x-raw ! interpipesink sync=false name=mixer_audio \

interpipesrc name=local_output listen-to=mixer_audio ! queue ! audio/x-raw ! autoaudiosink \


interpipesrc name=output1 listen-to=mixer_video ! queue ! video/x-raw,width=1920,height=1080,framerate=25/1 !  fpsdisplaysink \

interpipesrc name=output2 listen-to=mixer_video
	!  video/x-raw,width=1920,height=1080,framerate=25/1
	! videoconvert
	!  x264enc noise-reduction=10000 speed-preset=fast tune=zerolatency byte-stream=true threads=4 key-int-max=15 intra-refresh=true
	!  muxer.
interpipesrc listen-to=mixer_audio name=output3
	! avenc_ac3
	!  muxer.
mpegtsmux  name=muxer
  ! tcpserversink host=0.0.0.0 port=5004  recover-policy=keyframe sync-method=latest-keyframe sync=false \
 \
compositor name=mix \
  ! identity name=sig \
  ! interpipesink name=mixer_video caps=video/x-raw,width=1920,height=1080,framerate=25/1 
  sync=true async=false forward-eos=true \
   \
 interpipesrc \
    name=pipe1 \
    listen-to=s1 \
    format=time \
! mix.
```

i am trying to have a compositor, with a interpipesource "video_mixer"
the video mixer, listens to "video_source1" (and can be changed on the fly)
(this part works like a charm)

also i have multiple outputs (fpsdisplaysink, tcpserversink) which listen to interpipesrc=video_mixer
(works also perfectly)

now i am trying to do the same with audio, it works - (as above) with the autoaudiosink, via the "audio_mixer"

but as soon as i add:

```
interpipesrc listen-to=mixer_audio name=output3
	! avenc_ac3
	!  muxer.
```

the filesrc seems to be broken, and does not push/play anything.

changing the above with a audiotestsrc:

```
audiotestsrc listen-to=mixer_audio name=output3
  !avenc_ac3
  !muxer.
```

works, i get
  - local output (fpsdisplayoutput)
  - local audio output via `autoaudiosink`
  - tcp output
    - correct video from video_mixer
    - correct audiotestsrc

basic idea: change listen to from `audiocompositor`(audio)  and `mix`(video) - to cut to different sources.

anyone has a idea?

**Comment by rabidmonkeyman** [comment]
I'm running into a similar issue with audio and interpipesrc.

If i put all of the elements into one pipeline, it works fine. my video and audio is muxed together without issue:

> gst-client pipeline_create testing v4l2src device=/dev/video0 ! \   
> video/x-raw,width=1280,height=720,framerate=15/1 ! \   
> videoconvert ! \   
> x264enc speed-preset=3 tune=zerolatency key-int-max=10 ! \   
> queue ! \   
> mux. alsasrc device=hw:0,0 ! \    
> audioresample ! \   
> audioconvert ! \   
> avenc_ac3 ! \   
> queue ! \   
> mux. matroskamux name=mux ! \   
> filesink name=fs location=/mnt/userdata/video.mkv

However, if i split the audio up into another pipeline it stops working.

> gst-client pipeline_create audiosrcpipe alsasrc device=hw:0,0 ! \
> queue ! \
> interpipesink name=audiosrc sync=false caps=audio/x-raw

> gst-client pipeline_create testing v4l2src device=/dev/video0 ! \
> capsfilter name=cf caps=video/x-raw,width=1280,height=720,framerate=15/1 ! \
> videoconvert ! \
> x264enc speed-preset=3 tune=zerolatency key-int-max=10 ! \
> queue ! \
> mux. interpipesrc listen-to=audiosrc caps=audio/x-raw ! \
> audioresample ! \
> audioconvert ! \
> avenc_ac3 ! \
> queue ! \
> mux. matroskamux name=mux ! \
> filesink name=fs location=/mnt/userdata/video.mkv

with the above separated pipelines, ill get video but no audio. if i play around with the pipelines sometimes ill get no video and just audio or nothing at all. most of the time the pipeline doing the muxing wont even transition to the PLAYING state.

The video pipeline alone has worked for a long time but as soon as i started including a microphone for the audio, its never worked.

Im sorry i couldnt help the original issue but i figured my issue was similar enough that i could avoid creating another issue and maybe give this one more attention.

anyone have any ideas?

**Comment by dmacattack** [comment]
I am also having the identical problem with audio.

**Comment by TopperBG** [comment]
Here too problems with audio. Tried hard a lot of time and abandon audio :/

**Comment by vixp24** [comment]
I'm having similar problems with muxing video & audio using interpipes. Even a simple audio interpipe pair does not seem to work for me. Has anyone found a solution?

I am on gst-interpipe v1.0.5

**Comment by vixp24** [comment]
Update: 

Got it working by setting the "format" property on interepipesrc to 3 (GST_FORMAT_TIME). I found though that to mux in video & audio correctly, both the sources had to come from their own interpipesrc. Ie. I was not able to use interpipesrc only for video, and alsasrc for my microphone. 

Similar results on gst-interpipe v1.1.1

**Comment by TopperBG** [comment]
> Update:
> 
> Got it working by setting the "format" property on interepipesrc to 3 (GST_FORMAT_TIME). I found though that to mux in video & audio correctly, both the sources had to come from their own interpipesrc. Ie. I was not able to use interpipesrc only for video, and alsasrc for my microphone.
> 
> Similar results on gst-interpipe v1.1.1

You mean should have video to interpipesink and audio (alsasrc) to interpipesink and at the end combine both of them?
Could you be so kind post you gst construction lines.

**Comment by vixp24** [comment]
Yes, exactly. The pipelines should look something like this

**Video source**
rtspsrc ! rtph264depay ! h264parse ! "video/x-h264" ! queue ! interpipesink name=camera1 caps=video/x-h264

**Mic source**
alsasrc device="hw:2,0" ! queue ! audioconvert ! avenc_ac3 ! "audio/x-ac3" ! queue ! interpipesink name=audiopipesink caps=audio/x-ac3 sync=false async=false

**Combined sink (interpipe 1.1.1)**
interpipesrc name=camerasink listen-to=camera1 is-live=true allow-renegotiation=true format=3 ! queue ! h264parse ! mp4mux name=mux ! filesink location=test.mp4 interpipesrc name=audiosink listen-to=audiopipesink is-live=true allow-renegotiation=true format=3 ! mux.

**Comment by jcaballeros** [comment]
Closing issue. Feel free to reopen if necessary.
