### ISSUE TITLE
failed two tests

### ISSUE THREAD

**Issue by glenosborne** [RidgeRun/gst-interpipe#49]
tx2 jetpack 4.4

ubuntu 18.04

folowing tutorial 
https://devblogs.nvidia.com/building-multi-camera-media-server-ai-processing-jetson/

install gstinterpipe

https://developer.ridgerun.com/wiki/index.php?title=GstInterpipe_-_Building_and_Installation_Guide

====================================================
   GstInterpipe 1.1.1: tests/check/test-suite.log
====================================================

# TOTAL: 16
# PASS:  14
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: gst/test_enable_sync
==========================

Running suite(s): Interpipe
0%: Checks: 1, Failures: 1, Errors: 0
gst/test_enable_sync.c:71:F:interpipe_enable_sync:interpipe_enable_sync:0: Failure 'error' occurred
Check suite gst_interpipe ran in 0.009s (tests failed: 1)
FAIL gst/test_enable_sync (exit status: 1)

FAIL: gst/test_interpipe_synchronization
========================================

Running suite(s): Interpipe
0%: Checks: 1, Failures: 1, Errors: 0
gst/test_interpipe_synchronization.c:107:F:interpipe_synchronization:interpipe_synchronization:0: Failure 'buffer_timestamp2 < buffer_timestam$
Check suite gst_interpipe ran in 0.014s (tests failed: 1)
FAIL gst/test_interpipe_synchronization (exit status: 1)

What can i do to get these tests to pass?

regards

**Comment by glenosborne** [comment]
html/GstInterPipeIListener.html:196: warning: no link for: "GstCaps" -> (<span class="type">GstCaps</span>).
html/GstInterPipeIListener.html:315: warning: no link for: "GstBuffer" -> (<span class="type">GstBuffer</span>).
html/GstInterPipeIListener.html:357: warning: no link for: "GstEvent" -> (<span class="type">GstEvent</span>).
html/GstInterPipeSrc.html:73: warning: no link for: "GstInterPipeSrcStreamSync" -> (<span class="type">GstInterPipeSrcStreamSync</span>).

**Comment by glenosborne** [comment]
gtc-2020-demo/python-example$ gstd -k
gstd: error while loading shared libraries: libgstd-core.so.0: cannot open shared object file: No such file or directory

**Comment by glenosborne** [comment]
are these errors related to my initial failed tests?
thanks

**Comment by Santiago-vdk** [comment]
Same error. Could the plugin still function without these tests passing?

**Comment by anilgond** [comment]
I am also getting the same issue, 2 same tests failed. 
Interpipe programs are giving error, unable to create pipeline using interpipe.
I don't know what to do.

**Comment by cbstryker** [comment]
I'm also seeing this problem. Using Ubuntu 20.04

**Comment by jcaballeros** [comment]
Hi all,

I was able to reproduce the tests failure and will be debugging the issue. Thanks for your reports.

**Comment by jcaballeros** [comment]
Hi all,

This issue has been resolved in v1.1.2. If after pulling the new version you still have test issues, please open a new ticket.
