### ISSUE TITLE
Tests failing and EVENT_CAPS

### ISSUE THREAD

**Issue by bshankstd** [RidgeRun/gst-interpipe#5]
As mentioned in #2, the tests are still failing with `Sticky event misordering, got 'segment' before 'caps'` errors.

I'm also trying to use interpipe with an RTSP server, with a pipeline feeding H264 into an `interpipesink` and the RTSP server starting a pipeline of `interpipesrc ! rtph264pay` when a client connects. It fails with this error from the payloader: `error: No input format was negotiated, i.e. no caps event was received`.

For this problem and the tests, it seems like the `interpipesrc` is never sending EVENT_CAPS downstream. Is there a fix for this?

**Comment by michaelgruner** [comment]
@rrcarlosrodriguez you've dealt with this on the past right? Can you verify this use case?

**Comment by rrcarlosrodriguez** [comment]
Hi, I just checked and the tests are failing as mentioned! I'll be checking this and provide a fix.

Also, I've done tests using the rtph264pay before and it worked fine. Could you please paste the pipeline that you are using in order to reproduce the issue easily?

**Comment by bshankstd** [comment]
Great, looking forward to that fix. The pipeline being created by the GstRTSPMediaFactory is very simple, just `( interpipesrc listen-to="video" ! rtph264pay name=pay0 )`. The sink is being fed with `video/x-h264, stream-format=byte-stream, alignment=au` and is receiving buffers normally. I'm setting `forward-events=TRUE` on the sink but it doesn't seem to make a difference.

**Comment by bshankstd** [comment]
One possible factor I noticed is that when the RTSP pipeline is created, `interpipesrc` starts listening to the node before the `rtph264pay` is even created. This means the `src_negotiated` check in `gst_inter_pipe_sink_add()` couldn't be true (the `interpipesrc` isn't linked to anything yet), and no events sent there could be handled.

I think the correct solution is that if the BaseSrc isn't started yet (`GST_BASE_SRC_IS_STARTED()`), the `PROP_LISTEN_TO` setter should just save the node name and not start listening. An implementation of the BaseSrc `start()` function (called later when it changes to PAUSED state) should start the listening.

Similarly, removing the listener should take place in the BaseSrc `stop()` function rather than `finalize()`

**Comment by rrcarlosrodriguez** [comment]
Hi @bshankstd  I have been testing and found some use cases like yours which have some problems. We will be starting adding some support to handle the events better. Since the caps event is being handled different from the other events, it seems like there could be some mismatch. Also I found errors in the buffer timestamp compensation, so it could be causing some problems too.

I will let you know as soon I get something to test. Thanks for your interest and help testing our interpipes!

**Comment by bshankstd** [comment]
Good to hear! I've been testing some changes which have helped with the caps:
* in `interpipesrc`, don't start listening until the src has started
* in `interpipesink`, in `add_listener` if the src is not negotiated, get the sticky caps event from the sink pad and set those caps on the listening src.

This seems to solve the caps problems, but I then hit the timing problems you mentioned.
The RTSP streaming doesn't work, `interpipesrc` just receives and queues up buffers forever, and with gdb I can see the RTP streaming thread is pushing a buffer and waiting for a clock time which never seems to return. The `interpipe` sink and src pipeline are both driven by `GstSystemClock`, so that shouldn't be causing a problem.

**Comment by bshankstd** [comment]
I just pushed a fix for the timing issues, and interpipe is working well for my RTSP streaming. Although maybe there's a different way the timestamp synchronization can be done: could `gst_pad_set_offset()` could be used on the src pad?

I also have 
```
gst_base_src_set_format(GST_BASE_SRC(src), GST_FORMAT_TIME);
gst_base_src_set_live(GST_BASE_SRC(src), TRUE);
```
hardcoded in `gst_inter_pipe_src_init()`, this is kind of a hack. Maybe a check in `gst_inter_pipe_sink_add_listener()` could set format/live options on the listener.

**Comment by jcaballeros** [comment]
Hi,

I’m closing this issue because it has been inactive for a long time. Please feel free to reopen if you still encounter related issues.
