### ISSUE TITLE
Recording usb camera using interpipe fails

### ISSUE THREAD

**Issue by prabathdj** [RidgeRun/gst-interpipe#54]
Hi,
I tired to record a usb camera source in jetson nano using the below method using interpipes

`gst-client pipeline_create pipe1 v4l2src device=/dev/video0 ! interpipesink name=vid sync=false async=false`

`gst-client pipeline_create pipe3 interpipesrc listen-to=vid is-live=false ! 'video/x-raw, framerate=30/1, format=YUY2' ! nvvidconv ! 'video/x-raw(memory:NVMM),format=NV12' ! omxh264enc ! mpegtsmux ! filesink location="/tmp/rrcam.ts" sync=false async=false`

`gstd-client pipeline_play pipe1`

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "name" : "state",
    "value" : "PLAYING",
    "param" : {
        "description" : "The state of the pipeline",
        "type" : "GstdStateEnum",
        "access" : "((GstdParamFlags) READ | 2)"
    }
}
}

`gstd-client pipeline_play pipe3`

{
  "code" : 0,
  "description" : "Success",
  "response" : {
    "name" : "state",
    "value" : "PLAYING",
    "param" : {
        "description" : "The state of the pipeline",
        "type" : "GstdStateEnum",
        "access" : "((GstdParamFlags) READ | 2)"
    }
}
}

**The file is not created**. What can be the issue?

**Comment by jcaballeros** [comment]
Hi @prabathdj,

Try adding the caps between the v4l2src and the interpipesink. For instance, the following pipelines work for me:

`gst-client pipeline_create pipe1 v4l2src device=/dev/video0 ! 'video/x-raw, framerate=30/1, format=YUY2' ! interpipesink name=vid sync=false async=false
`

`gst-client pipeline_create pipe3 interpipesrc listen-to=vid is-live=false ! 'video/x-raw, framerate=30/1, format=YUY2' ! nvvidconv ! 'video/x-raw(memory:NVMM),format=NV12' ! omxh264enc ! mpegtsmux ! filesink location="/tmp/rrcam.ts" sync=false async=false
`

**Comment by prabathdj** [comment]
Thank you I will try this method

**Comment by prabathdj** [comment]
`gst-client pipeline_create pipe3 interpipesrc **name=src format=time** listen-to=vid is-live=false ! 'video/x-raw, framerate=30/1, format=YUY2' ! nvvidconv ! 'video/x-raw(memory:NVMM),format=NV12' ! omxh264enc ! mpegtsmux ! filesink location="/tmp/rrcam.ts" sync=false async=false`

by adding this solved the problem for me
