### ISSUE TITLE
Recording wont start with gstd commands

### ISSUE THREAD

**Issue by prabathdj** [RidgeRun/gst-interpipe#57]
Hi
I am testing the below pipelines using gstd

`gst-client pipeline_create pipe1 v4l2src device=/dev/video1 ! 'video/x-raw, format=(string)YUY2, width=(int)1920, height=(int)1080, framerate=(fraction)30/1' ! nvvidconv ! 'video/x-raw(memory:NVMM),format=RGBA' ! interpipesink name=ch1 sync=false async=false`

`gst-client pipeline_create pipe9 interpipesrc name=src format=time listen-to=ch1 ! nvv4l2h264enc maxperf-enable=1 bitrate=4000000 profile=4 ! h264parse ! mux. pulsesrc device="alsa_input.usb-VXIS_Inc_ezcap_U3_capture-02.analog-stereo" ! audio/x-raw,width=16,depth=16,rate=44100,channel=1 ! queue ! audioconvert ! voaacenc ! aacparse ! mpegtsmux name=mux ! filesink location="/tmp/addd.ts" sync=false async=false`

`gst-client pipeline_play pipe1`

`gst-client pipeline_play pipe9`

The pipeleines are created without errors and when played  the state changes to playing state without errors. But the file is not created

I test the below command using gst-launch and interpipes its working 
 
`gst-launch-1.0 -e v4l2src device=/dev/video1 ! 'video/x-raw, format=(string)YUY2, width=(int)1920, height=(int)1080, framerate=(fraction)30/1' ! nvvidconv ! 'video/x-raw(memory:NVMM),format=NV12' ! interpipesink name=vid interpipesrc name=src format=time listen-to=vid ! nvv4l2h264enc maxperf-enable=1 bitrate=4000000 profile=4 ! h264parse ! mux. pulsesrc device="alsa_input.usb-VXIS_Inc_ezcap_U3_capture-02.analog-stereo" ! audio/x-raw,width=16,depth=16,rate=44100,channel=1 ! queue ! audioconvert ! voaacenc ! aacparse ! mpegtsmux name=mux ! filesink location="addds.ts"`

How to resolve this error?

**Comment by jcaballeros** [comment]
Hi @prabathdj,

The problem is that in your gstd pipe1 you convert to RGBA and the nvv4l2h264enc element in pipe9 doesn't support RGBA in its input. Your gst-launch pipeline works because ther you convert to NV12 instead of RGBA, and nvv4l2h264enc supports NV12. To check the caps allowed in an element input, say nvv4l2h264enc, you can run **gst-inspect-1.0 nvv4l2h264enc** and check the sink pad capabilities, for instance I get:

```
  SINK template: 'sink'
    Availability: Always
    Capabilities:
      video/x-raw(memory:NVMM)
                  width: [ 1, 2147483647 ]
                 height: [ 1, 2147483647 ]
                 format: { (string)I420, (string)NV12, (string)P010_10LE }
              framerate: [ 0/1, 2147483647/1 ]

```

Also, I recommend to add a capsfilter after the interpipesrc in pipe9, you take the following pipelines as reference:

```
gst-client pipeline_create pipe1 v4l2src device=/dev/video1 ! capsfilter caps="video/x-raw,format=YUY2,width=640,height=480,framerate=30/1" ! nvvidconv ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12" ! interpipesink name=ch1 sync=false async=false

gst-client pipeline_create pipe9 interpipesrc name=src format=time listen-to=ch1 ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=640,height=480,framerate=30/1" ! nvv4l2h264enc maxperf-enable=1 bitrate=4000000 profile=4 ! h264parse ! mux. pulsesrc device="alsa_input.usb-046d_HD_Pro_Webcam_C920_406ED6AF-02.analog-stereo" ! audio/x-raw,width=16,depth=16,rate=44100,channel=1 ! queue ! audioconvert ! voaacenc ! aacparse ! mpegtsmux name=mux ! filesink location="/tmp/addd.ts" sync=false async=false
```

**Comment by prabathdj** [comment]
Hi @jcaballeros ,

Thank you for your reply. It was very helpful, but I have still few issues to be sorted.

I tried the pipelines without muxing the audio. The pipeleine is working perfectly without any errors.

`gst-client pipeline_create pipe1 v4l2src device=/dev/video1 ! capsfilter caps="video/x-raw,format=YUY2,width=1280,height=720,framerate=30/1" ! nvvidconv ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12" ! interpipesink name=ch1 sync=false async=false`

`gst-client pipeline_create pipe9 interpipesrc name=src format=time listen-to=ch1 ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=1280,height=720,framerate=30/1" ! nvv4l2h264enc maxperf-enable=1 bitrate=4000000 profile=4 ! h264parse ! mpegtsmux name=mux ! filesink location="/tmp/addd.ts" sync=false async=false`

As soon as the audio is added as shown below the file created is loosing a large amount of frames and sometimes the recording wont start.

`gst-client pipeline_create pipe1 v4l2src device=/dev/video1 ! capsfilter caps="video/x-raw,format=YUY2,width=1280,height=720,framerate=30/1" ! nvvidconv ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12" ! interpipesink name=ch1 sync=false async=false`

`gst-client pipeline_create pipe9 interpipesrc name=src format=time listen-to=ch1 ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=1280,height=720,framerate=30/1" ! nvv4l2h264enc maxperf-enable=1 bitrate=4000000 profile=4 ! h264parse ! mux. pulsesrc device="alsa_input.usb-VXIS_Inc_ezcap_U3_capture-02.analog-stereo" ! 'audio/x-raw,width=16,depth=16,rate=44100,channel=1' ! audioconvert ! voaacenc ! aacparse ! mpegtsmux name=mux ! filesink location="/tmp/addd.ts" sync=false async=false`

Is there a issue in the pipeline or is there any method to add USB audio? 
Can I use create another interpipesink separately to the pipline instead of mux?

Thank you

**Comment by jcaballeros** [comment]
Hi,

This seems like a timestamp synchronization issue. Try setting the interpipesrc property stream-sync to restart-ts to see if it helps.

**Comment by prabathdj** [comment]
Thank you @jcaballeros. This fixed the recording problem with audio. I've tried this solution to record a Picture In Picture video using two usb video sources using the below pipelines

`gst-client pipeline_create pipe1 v4l2src device=/dev/video1 ! capsfilter caps="video/x-raw,format=YUY2,width=1920,height=1080,framerate=30/1" ! nvvidconv ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12" ! interpipesink name=ch1 sync=false async=false`

`gst-client pipeline_create pipe2 v4l2src device=/dev/video0 ! capsfilter caps="video/x-raw,format=YUY2,width=640,height=480,framerate=30/1" ! nvvidconv ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12" ! interpipesink name=ch2 sync=false async=false`

`gst-client pipeline_create pipe5 interpipesrc name=src listen-to=ch1 format=time stream-sync=restart-ts ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=1920,height=1080,framerate=30/1" ! comp.sink_0 interpipesrc name=src2 listen-to=ch2 format=time stream-sync=restart-ts ! capsfilter caps="video/x-raw(memory:NVMM),format=NV12,width=640,height=480,framerate=30/1" ! comp.sink_1 nvcompositor name=comp sink_0::xpos=0 sink_0::ypos=0 sink_1::xpos=1500 sink_1::ypos=800 sink_1::width=320 sink_1::height=240 ! nvvidconv ! nvv4l2h264enc maxperf-enable=1 bitrate=4000000 profile=4 ! h264parse ! mux. pulsesrc device="alsa_input.usb-VXIS_Inc_ezcap_U3_capture-02.analog-stereo" ! 'audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=44100, channels=(int)2' ! queue ! audioconvert ! voaacenc ! aacparse ! mpegtsmux name=mux ! filesink location="/tmp/pipinters.ts" sync=false async=false`

The recorded file's video is highly distorted. 
I've tried the pipelines without stream-sync-restart-ts then the video looses lots of frames

What can be the issue for this scenario?

Thank You

**Comment by prabathdj** [comment]
Hi @jcaballeros ,

I was able to sort out the issue.  The problem was in placing the caps in the correct place. Thank you for the support.
