### ISSUE TITLE
can interpipe be used to communicate between 2 processes?

### ISSUE THREAD

**Issue by braindevices** [RidgeRun/gst-interpipe#61]
is this purely used to communicate within a single process? If not, can you provide some example about how to use it?

**Comment by michaelgruner** [comment]
Hello,

No, interpipes will share buffers in the same process only.

For Inter process take a look at:
https://gstreamer.freedesktop.org/documentation/ipcpipeline/index.html?gi-language=c

Michael

**Comment by braindevices** [comment]
@michaelgruner thanks a lot

**Comment by michaelgruner** [comment]
you're welcome.
