### ISSUE TITLE
Multiple interpipesrc elements in the same pipeline

### ISSUE THREAD

**Issue by garygumdrops** [RidgeRun/gst-interpipe#64]
Hi

Is it possible to have multiple interpipesrc elements within the same pipeline? The use-case I have in mind is to have one interpipesrc element for each sink pad on a compositor.

I would then be able to connect up multiple video decoder pipelines whose interpipesink elements would connect to newly created interpipesink elements connected to a sink pad on the compositor.

The compositor would then arrange for the video stream from each decoder pipeline to be displayed within its own area on the display.

**Comment by michaelgruner** [comment]
Hi Gary

Yes, this is a completely valid use case of the interpipes. We’ve done very similar configurations ourselves.

Michael

**Comment by jcaballeros** [comment]
Closing, feel free to reopen if necessary.
